#!/bin/bash

: "${DATA_DIR:=$(cd "$(dirname "${BASH_SOURCE[0]}")"/../../data && pwd)}"
export DATA_DIR
./hotspot.out 1024 4 10000 ${DATA_DIR}/hotspot/temp_1024 ${DATA_DIR}/hotspot/power_1024 output.txt $@
