#!/bin/bash

./hotspot.out 64 1 1 ../../data/hotspot/temp_64 ../../data/hotspot/power_64 output.txt -p 0 -d 0 --ref nvidia-ref-64-1-1.txt
#./hotspot.out 1024 4 10000 ../../data/hotspot/temp_1024 ../../data/hotspot/power_1024 output.txt $@
