#!/bin/bash

#./kmeans.out -o -r -i ./32_34.txt -p 0 -d 0
# ./kmeans.out -o -r -i ../../data/kmeans/100 -g nvidia_result_100_k5 -p 0 -d 0
# ./kmeans.out -o -r -i ../../data/kmeans/256_34f.txt -g nvidia_result_256_34f_k5 -p 0 -d 0
./kmeans.out -o -r -i ../../data/kmeans/512_34f.txt -g nvidia_result_512_34f_k5 -p 0 -d 0
# ./kmeans.out -o -r -i ../../data/kmeans/4096_34f.txt -g nvidia_result_4096_34f_k5 -p 0 -d 0
